-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:10:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `capacitacao` ;

-- -----------------------------------------------------
-- Table `capacitacao`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Instrutor` (
  `idInstrutor` 	INT NOT NULL,
  `nome` 			VARCHAR(100) NOT NULL,
  `email`			VARCHAR(100) NOT NULL,
  `valor_Hora`		DOUBLE NOT NULL,
  `certificados` 	VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Curso` (
  `id_Curso` 		INT NOT NULL,
  `nome` 			VARCHAR(100) NOT NULL,
  `requisito` 		VARCHAR(100) NOT NULL,
  `carga_Horaria` 	DOUBLE NOT NULL,
  `preco` 			DOUBLE NOT NULL,
  PRIMARY KEY (`id_Curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Turma` (
  `idTurma` 				INT NOT NULL,
  `carga_horária` 			DOUBLE NOT NULL,
  `data_Inicial` 			DATE NOT NULL,
  `data_Final` 				DATE NOT NULL,
  `Instrutor_idInstrutor` 	INT NOT NULL, -- chave estrangeira
  `Curso_id_Curso` 			INT NOT NULL, -- chave estrangeira 
  PRIMARY KEY (`idTurma`, `Instrutor_idInstrutor`, `Curso_id_Curso`),
  -- INDEX `fk_Turma_Instrutor_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  -- INDEX `fk_Turma_Curso1_idx` (`Curso_id_Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Instrutor`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `capacitacao`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Curso_id_Curso`)
    REFERENCES `capacitacao`.`Curso` (`id_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Aluno` (
  `idAluno` 			INT NOT NULL,
  `nome` 				VARCHAR(100) NOT NULL,
  `cpf` 				VARCHAR(15) NOT NULL,
  `dataNasc`			DATE NOT NULL,
  `fone` 				CHAR(14) NOT NULL,
  `email` 				VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Matricula` (
  `id_Matricula` 		INT NOT NULL,
  `data_Matricula` 		DATE NOT NULL,
  `Turma_idTurma` 		INT NOT NULL, -- chave estrangeira
  `Aluno_idAluno` 		INT NOT NULL, -- chave estrangeira
  PRIMARY KEY (`id_Matricula`),
  -- INDEX `fk_Matricula_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  -- INDEX `fk_Matricula_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `capacitacao`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `capacitacao`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
